language: php
php:
  - 7.2

cache:
  directories:
    - ${HOME}/.composer/cache
    - ./bin/.phpunit

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo chown -R ${UID:-1000}:${GID:-1000} $PWD
  - sudo chown -R ${UID:-1000}:${GID:-1000} ${HOME}/.yarn
  - sudo chown -R ${UID:-1000}:${GID:-1000} ${HOME}/.composer
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - cp .env.test.local.travis .env.test.local
  - docker network create study-onbilling_default

install:
  - docker-compose build
  - docker-compose up -d
  - docker-compose exec php composer install
  - docker-compose exec php bin/console doctrine:database:create --env=test
  - docker-compose exec php bin/console doctrine:migrations:migrate --env=test --no-interaction
  - docker-compose exec php bin/console doctrine:fixtures:load --env=test --no-interaction
  - docker-compose run node yarn install
  - docker-compose run node yarn encore dev

script:
  - docker-compose exec php bin/phpunit

after_script:
  - docker-compose down