<?php


namespace App\Tests\Mock;

use App\Entity\Course;
use App\Exception\BillingAuthException;
use App\Security\User;
use App\Service\BillingClient;
use App\Service\DecodeJwt;
use Symfony\Component\Serializer\SerializerInterface;

class BillingClientMock extends BillingClient
{
    public function auth(string $request): array
    {
        // Получаем запрос.
        $data = json_decode($request, true);
        // Если в запресе указан пользователь test, то отдаем токен.
        if ($data['username'] === 'test@gmail.com' && $data['password'] === 'general_user') {
            return [
                'token' => $this->generateToken('test@gmail.com'),
                'username' => 'test@gmail.com',
                'roles' => ["ROLE_USER"],
                'refresh_token' => '23123'
            ];
        }
        // Если в запресе указан администратор admin, то отдаем токен.
        if ($data['username'] === 'admin@gmail.com' && $data['password'] === 'super_admin') {
            return [
                'token' => $this->generateToken('admin@gmail.com'),
                'username' => 'admin@gmail.com',
                'roles' => ["ROLE_SUPER_ADMIN", "ROLE_USER"],
                'refresh_token' => '23123'
            ];
        }
        // иначе вызываем исключение билинга. Это тождественно тому, что сервис не нашел пользователя.
        throw new BillingAuthException('Пользователь не найден.');
    }

    public function register(string $request): array
    {
    }

    public function refreshUser(string $refresh_token): array
    {
        return parent::refreshUser($refresh_token); // TODO: Change the autogenerated stub
    }

    public function getCurrentUser(User $user, DecodeJwt $decodeJwt, SerializerInterface $serializer): array
    {
        // Формируем ответ
        $response = [
            'username' => null,
            'balance' => null
        ];

        if ($user->getUsername() === 'test@gmail.com') {
            $response['username'] = 'test@gmail.com';
            $response['balance'] = 10;
        } elseif ($user->getUsername() === 'admin@gmail.com') {
            $response['username'] = 'test@gmail.com';
            $response['balance'] = 100;
        }

        return $response;
    }

    private function generateToken(string $username): string
    {
        $roles = null;
        if ($username === 'test@gmail.com') {
            $roles = ['ROLE_USER'];
        } elseif ($username === 'admin@gmail.com') {
            $roles = ["ROLE_SUPER_ADMIN", "ROLE_USER"];
        }
        $dataPayload = [
            'username' => $username,
            'roles' => $roles,
            'exp' => (new \DateTime('+ 1 hour'))->getTimestamp(),
        ];
        $payload = base64_encode(json_encode($dataPayload));
        return 'header.' . $payload . '.signature';
    }

    public function getCourses(User $user): array
    {
        return [
            [
                'code' => 'Introduction-to-Data-Analysis-and-Machine-Learning',
                'type' => 'rent',
                'price' => 100
            ],
            [
                'code' => 'Web-Designer',
                'type' => 'free'
            ],
            [
                'code' => 'Internet-Marketer',
                'type' => 'buy',
                'price' => 500
            ],
            [
                'code' => 'Business-Analyst',
                'type' => 'rent',
                'price' => 50
            ]
        ];
    }

    public function getCourse(User $user, Course $course): array
    {
        if ($course->getCode() === 'Introduction-to-Data-Analysis-and-Machine-Learning') {
            return [
                'code' => 'Introduction-to-Data-Analysis-and-Machine-Learning',
                'type' => 'rent',
                'price' => 100
            ];
        }

        if ($course->getCode() === 'Web-Designer') {
            return [
                'code' => 'Web-Designer',
                'type' => 'free'
            ];
        }

        if ($course->getCode() === 'Internet-Marketer') {
            return [
                'code' => 'Internet-Marketer',
                'type' => 'buy',
                'price' => 500
            ];
        }

        if ($course->getCode() === 'Business-Analyst') {
            return [
                'code' => 'Business-Analyst',
                'type' => 'rent',
                'price' => 50
            ];
        }

        return [];
    }

    public function getUserCourses(User $user): array
    {
        return [
            [
                'code' => 'Business-Analyst',
                'cost' => 50,
                'type' => 'rent',
                'expires_at' => '2021-05-03T21:20:10+00:00'
            ],
            [
                'code' => 'Internet-Marketer',
                'cost' => 500,
                'type' => 'buy'
            ]
        ];
    }

    public function paymentCourse(User $user, Course $course): array
    {
        return [
            'success' => true,
            'course_type' => 'rent',
            'expires_at' => '2021-05-20T13:46:07+00:00'
        ];
    }

    public function getTransactions(User $user): array
    {
        return [
            [
                'id' => 8,
                'created_at' => '2021-04-26T08:18:04+00:00',
                'type' => 'deposit',
                'amount' => 1000
            ],
            [
                'id' => 20,
                'created_at' => '2021-04-26T18:20:10+00:00',
                'skip_expired' => '2021-05-03T21:20:10+00:00',
                'type' => 'payment',
                'course_code' => 'Business-Analyst',
                'amount' => 50
            ],
        ];
    }
}
